//GET all games
GET http://localhost:5204/games


### //GET game by id
GET http://localhost:5204/games/2

### //POST new game
POST http://localhost:5204/games
Content-Type: application/json

{
    
    "genre": "game2 genre",
    "price": 9.99,
    "releaseDate": "2019-08-01"
}

### //PUT update game
PUT http://localhost:5204/games/1
Content-Type: application/json

{
    "name": "Street Fighter V",
    "genre": "Fighting",
    "price": 10.00,
    "releaseData": "2021-01-01"
  }

### //DELETE game
DELETE http://localhost:5204/games/3